-- ====================================================================
-- Khatabook CRM - Supabase PostgreSQL Database Schema
-- Run this script in the Supabase SQL Editor (Dashboard -> SQL Editor)
-- ====================================================================

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create Leads Table
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    composite_key TEXT UNIQUE NOT NULL,
    entity_id TEXT NOT NULL,
    entity_type TEXT NOT NULL DEFAULT 'company',
    name TEXT NOT NULL,
    state TEXT DEFAULT 'N/A',
    district TEXT DEFAULT 'N/A',
    roc TEXT DEFAULT 'N/A',
    nic_code TEXT DEFAULT 'N/A',
    nic_label TEXT DEFAULT 'N/A',
    class_of_company TEXT DEFAULT 'Private',
    date_of_incorporation TEXT DEFAULT 'N/A',
    paid_up_capital NUMERIC DEFAULT 0,
    email TEXT,
    director_name TEXT DEFAULT 'N/A',
    director_email TEXT,
    director_mobile TEXT,
    authorized_capital NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'New',
    notes JSONB DEFAULT '[]'::jsonb,
    batch_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Monthly Batches Table
CREATE TABLE IF NOT EXISTS public.batches (
    id TEXT PRIMARY KEY,
    batch_name TEXT NOT NULL,
    upload_date TIMESTAMPTZ DEFAULT NOW(),
    total_rows_in_file INTEGER DEFAULT 0,
    new_records_count INTEGER DEFAULT 0,
    duplicate_records_count INTEGER DEFAULT 0,
    duplicate_strategy_used TEXT DEFAULT 'skip',
    file_name TEXT
);

-- 4. Create User Roles Table (Admin RBAC)
CREATE TABLE IF NOT EXISTS public.user_roles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'Admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Performance Indexes
CREATE INDEX IF NOT EXISTS idx_leads_composite_key ON public.leads(composite_key);
CREATE INDEX IF NOT EXISTS idx_leads_entity_id ON public.leads(entity_id);
CREATE INDEX IF NOT EXISTS idx_leads_state ON public.leads(state);
CREATE INDEX IF NOT EXISTS idx_leads_status ON public.leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_batch_id ON public.leads(batch_id);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- 7. Drop existing policies if re-running
DROP POLICY IF EXISTS "Allow public read access to leads" ON public.leads;
DROP POLICY IF EXISTS "Allow authenticated insert to leads" ON public.leads;
DROP POLICY IF EXISTS "Allow authenticated update to leads" ON public.leads;
DROP POLICY IF EXISTS "Allow authenticated delete to leads" ON public.leads;

DROP POLICY IF EXISTS "Allow public read access to batches" ON public.batches;
DROP POLICY IF EXISTS "Allow authenticated insert to batches" ON public.batches;

DROP POLICY IF EXISTS "Allow public read user_roles" ON public.user_roles;

-- 8. Create RLS Policies (Allow Read/Write for Authenticated and Public Access)
CREATE POLICY "Allow public read access to leads" ON public.leads FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert to leads" ON public.leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated update to leads" ON public.leads FOR UPDATE USING (true);
CREATE POLICY "Allow authenticated delete to leads" ON public.leads FOR DELETE USING (true);

CREATE POLICY "Allow public read access to batches" ON public.batches FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert to batches" ON public.batches FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read user_roles" ON public.user_roles FOR SELECT USING (true);

-- Done! Tables, Indexes, and RLS policies are completely configured for Khatabook CRM.
